using DinheiroSobControle.EntityFrameworkCore;
using Xunit;

namespace DinheiroSobControle.EntityFrameworkCore;

public class DinheiroSobControleEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<DinheiroSobControleEntityFrameworkCoreFixture>
{

}
