using Xunit;

namespace DinheiroSobControle.EntityFrameworkCore;

[CollectionDefinition(DinheiroSobControleTestConsts.CollectionDefinitionName)]
public class DinheiroSobControleEntityFrameworkCoreCollection : ICollectionFixture<DinheiroSobControleEntityFrameworkCoreFixture>
{

}
